version: '2'
services:
  session-db:
    image: mysql
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: session-db
  session-ms:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - session-db
